import type { Payment } from "./payment-types";

export const mockPayments: Payment[] = [
  {
    id: "p1",
    tenantName: "Rohit Sharma",
    tenantAvatar: "RS",
    room: "R-101",
    propertyName: "Gupta Boys Hostel",
    propertyId: "1",
    amount: "Rs.7,500",
    amountRaw: 7500,
    month: "Jun 2025",
    status: "paid",
    method: "upi",
    paidOn: "Jun 1, 2025",
    dueDate: "Jun 5, 2025",
    reference: "UPI/2025/06/001",
  },
  {
    id: "p2",
    tenantName: "Karan Singh",
    tenantAvatar: "KS",
    room: "R-207",
    propertyName: "Gupta Boys Hostel",
    propertyId: "1",
    amount: "Rs.8,000",
    amountRaw: 8000,
    month: "Jun 2025",
    status: "overdue",
    dueDate: "Jun 5, 2025",
    notes: "Not responding to reminders",
  },
  {
    id: "p3",
    tenantName: "Anil Kumar",
    tenantAvatar: "AK",
    room: "R-102",
    propertyName: "Gupta Boys Hostel",
    propertyId: "1",
    amount: "Rs.7,500",
    amountRaw: 7500,
    month: "Jun 2025",
    status: "paid",
    method: "cash",
    paidOn: "Jun 2, 2025",
    dueDate: "Jun 5, 2025",
    reference: "CASH/2025/06/002",
  },
  {
    id: "p4",
    tenantName: "Dinesh Kumar",
    tenantAvatar: "DK",
    room: "R-108",
    propertyName: "Gupta Boys Hostel",
    propertyId: "1",
    amount: "Rs.7,500",
    amountRaw: 7500,
    month: "Jun 2025",
    status: "overdue",
    dueDate: "Jun 5, 2025",
  },
  {
    id: "p5",
    tenantName: "Priya Mehta",
    tenantAvatar: "PM",
    room: "R-105",
    propertyName: "Gupta Girls PG",
    propertyId: "2",
    amount: "Rs.7,200",
    amountRaw: 7200,
    month: "Jun 2025",
    status: "paid",
    method: "upi",
    paidOn: "Jun 3, 2025",
    dueDate: "Jun 5, 2025",
    reference: "UPI/2025/06/005",
  },
  {
    id: "p6",
    tenantName: "Sneha Patel",
    tenantAvatar: "SP",
    room: "R-108",
    propertyName: "Gupta Girls PG",
    propertyId: "2",
    amount: "Rs.7,500",
    amountRaw: 7500,
    month: "Jun 2025",
    status: "paid",
    method: "bank",
    paidOn: "Jun 3, 2025",
    dueDate: "Jun 5, 2025",
    reference: "NEFT/2025/06/003",
  },
  {
    id: "p7",
    tenantName: "Arjun Verma",
    tenantAvatar: "AV",
    room: "R-201",
    propertyName: "Gupta Boys Hostel",
    propertyId: "1",
    amount: "Rs.8,000",
    amountRaw: 8000,
    month: "Jun 2025",
    status: "pending",
    dueDate: "Jun 10, 2025",
  },
  {
    id: "p8",
    tenantName: "Ravi Tiwari",
    tenantAvatar: "RT",
    room: "R-209",
    propertyName: "Gupta Boys Hostel",
    propertyId: "1",
    amount: "Rs.9,500",
    amountRaw: 9500,
    month: "Jun 2025",
    status: "overdue",
    dueDate: "Jun 5, 2025",
    notes: "Promised to pay by Jun 15",
  },
  {
    id: "p9",
    tenantName: "Vikram Mehta",
    tenantAvatar: "VM",
    room: "R-109",
    propertyName: "Gupta Boys Hostel",
    propertyId: "1",
    amount: "Rs.9,000",
    amountRaw: 9000,
    month: "Jun 2025",
    status: "paid",
    method: "upi",
    paidOn: "Jun 2, 2025",
    dueDate: "Jun 5, 2025",
    reference: "UPI/2025/06/009",
  },
  {
    id: "p10",
    tenantName: "Divya Nair",
    tenantAvatar: "DN",
    room: "R-403",
    propertyName: "Sunrise Apartments",
    propertyId: "3",
    amount: "Rs.9,200",
    amountRaw: 9200,
    month: "Jun 2025",
    status: "paid",
    method: "bank",
    paidOn: "Jun 3, 2025",
    dueDate: "Jun 5, 2025",
    reference: "NEFT/2025/06/010",
  },
  {
    id: "p11",
    tenantName: "Rohit Sharma",
    tenantAvatar: "RS",
    room: "R-101",
    propertyName: "Gupta Boys Hostel",
    propertyId: "1",
    amount: "Rs.7,500",
    amountRaw: 7500,
    month: "May 2025",
    status: "paid",
    method: "upi",
    paidOn: "May 3, 2025",
    dueDate: "May 5, 2025",
    reference: "UPI/2025/05/001",
  },
  {
    id: "p12",
    tenantName: "Priya Mehta",
    tenantAvatar: "PM",
    room: "R-105",
    propertyName: "Gupta Girls PG",
    propertyId: "2",
    amount: "Rs.7,200",
    amountRaw: 7200,
    month: "May 2025",
    status: "paid",
    method: "upi",
    paidOn: "May 4, 2025",
    dueDate: "May 5, 2025",
    reference: "UPI/2025/05/005",
  },
];

export const mockProperties = [
  { id: "all", name: "All Properties" },
  { id: "1", name: "Gupta Boys Hostel" },
  { id: "2", name: "Gupta Girls PG" },
  { id: "3", name: "Sunrise Apartments" },
];

export const mockMonths = [
  "Jun 2025",
  "May 2025",
  "Apr 2025",
  "Mar 2025",
];
