import type { Property } from "./property-types";

export const mockProperties: Property[] = [
  {
    id: "1",
    name: "Gupta Boys Hostel",
    type: "hostel",
    address: "45 Koregaon Park Road",
    city: "Pune",
    state: "Maharashtra",
    floors: 4,
    totalRooms: 40,
    occupiedRooms: 36,
    monthlyRevenue: "Rs.3.1L",
    pendingDues: "Rs.48K",
    status: "active",
  },
  {
    id: "2",
    name: "Gupta Girls PG",
    type: "pg",
    address: "12 Baner Road, Baner",
    city: "Pune",
    state: "Maharashtra",
    floors: 3,
    totalRooms: 36,
    occupiedRooms: 32,
    monthlyRevenue: "Rs.2.6L",
    pendingDues: "Rs.22K",
    status: "active",
  },
  {
    id: "3",
    name: "Sunrise Apartments",
    type: "apartment",
    address: "78 Wakad Main Street",
    city: "Pune",
    state: "Maharashtra",
    floors: 5,
    totalRooms: 20,
    occupiedRooms: 20,
    monthlyRevenue: "Rs.1.4L",
    pendingDues: "Rs.0",
    status: "active",
  },
];